# Generated by Django 6.0.5 on 2026-05-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='enquiry',
            constraint=models.UniqueConstraint(fields=('email', 'phone'), name='unique_email_phone_enquiry'),
        ),
    ]
