# Generated by Django 6.0.5 on 2026-05-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_enquiry_options_enquiry_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('cctv', 'CCTV'), ('biometric', 'Biometric'), ('solar', 'Solar'), ('enterprise', 'Enterprise'), ('maintenance', 'Maintenance')], max_length=50)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
